db:
  username: "skilvul"
  password: "skilvul123apa"
  db-name: "skilvul-groupchat"
  port: "5432"
  address: "34.101.216.10"
redis:
  host: "34.101.216.10"
  password: "skilvulredis"
jwt:
  sign-key: "signedK3y"